{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavTo_AspirantesCreateKR"
	},
	"PageToOpen": "/DreamsBank/Pages/KnowledgeRun/Datos maestros/Aspirante_Create.page",
	"ModalPage": true
}