{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "create"
	},
	"OnFailure": "/DreamsBank/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Aspirante",
		"Service": "/DreamsBank/Services/dreamsbankmov.service"
	},
	"Properties": {
		"identificacion": "#Control:identificacion/#Value",
		"nombre": "#Control:nombre/#Value",
		"edad": "#Control:edad/#Value",
		"ciudad": "#Control:ciudad/#Value",
		"semestre": "#Control:semestre/#Value",
		"carrera": "#Control:carrera/#Value",
		"fechaNacimiento": "#Control:fechaNacimiento/#Value",
		"ciudadNacimiento": "#Control:ciudadNacimiento/#Value",
		"telefono": "#Control:telefono/#Value",
		"correo": "#Control:correo/#Value",
		"direccion": "#Control:direccion/#Value",
		"contrasena": "#Control:contrasena/#Value",
		"haAspirado": false,
		"universidad": "#Control:universidad/#Value",
		"fecha_creacion": "/DreamsBank/Rules/traer_fecha.js",
		"modulo": "#Control:modulo/#Value"
	}
}