{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Aspirante",
		"Service": "/DreamsBank/Services/dreamsbankmov.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"identificacion": "#Control:identificacion/#Value",
		"nombre": "#Control:nombre/#Value",
		"edad": "#Control:edad/#Value",
		"ciudad": "#Control:ciudad/#Value",
		"semestre": "#Control:semestre/#Value",
		"carrera": "#Control:carrera/#Value",
		"fechaNacimiento": "#Control:fechaNacimiento/#Value",
		"ciudadNacimiento": "#Control:ciudadNacimiento/#Value",
		"telefono": "#Control:telefono/#Value",
		"correo": "#Control:correo/#Value",
		"direccion": "#Control:direccion/#Value",
		"universidad": "#Control:universidad/#Value"
	}
}