{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Donante",
        "Service": "/DreamsBank/Services/dreamsbankmov.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "identificacion": "#Control:identificacion/#Value",
        "tipo": "#Control:tipo/#Value",
        "nombre": "#Control:nombre/#Value",
        "edad": "#Control:edad/#Value",
        "ciudad": "#Control:ciudad/#Value",
        "empresa": "#Control:empresa/#Value",
        "telefono": "#Control:telefono/#Value",
        "correo": "#Control:correo/#Value",
        "imagen": "#Control:imagen/#Value",
        "web": "#Control:web/#Value",
        "direccion": "#Control:direccion/#Value",
        "contrasena": "#Control:contrasena/#Value",
        "fechaNacimiento": "#Control:fechaNacimiento/#Value",
        "idProducto_id": "#Control:idProducto_id/#SelectedValue",
        "haDonado": "#Control:haDonado/#Value",
        "generico1": "#Control:generico1/#Value",
        "generico2": "#Control:generico2/#Value",
        "generico3": "#Control:generico3/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action"
}