{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Donante",
		"Service": "/DreamsBank/Services/dreamsbankmov.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"identificacion": "#Control:identificacion/#Value",
		"nombre": "#Control:nombre/#Value",
		"edad": "#Control:edad/#Value",
		"ciudad": "#Control:ciudad/#Value",
		"empresa": "#Control:empresa/#Value",
		"telefono": "#Control:telefono/#Value",
		"correo": "#Control:correo/#Value",
		"web": "#Control:web/#Value",
		"direccion": "#Control:direccion/#Value",
		"fechaNacimiento": "#Control:fechaNacimiento/#Value"
	}
}