{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Donante",
		"Service": "/DreamsBank/Services/dreamsbankmov.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"identificacion": "#Control:identificacion/#Value",
		"tipo": "#Control:tipo/#Value",
		"nombre": "#Control:nombre/#Value",
		"edad": "#Control:edad/#Value",
		"ciudad": "#Control:ciudad/#Value",
		"empresa": "#Control:empresa/#Value",
		"telefono": "#Control:telefono/#Value",
		"correo": "#Control:correo/#Value",
		"imagen": "#Control:imagen/#Value",
		"web": "#Control:web/#Value",
		"direccion": "#Control:direccion/#Value",
		"contrasena": "#Control:contrasena/#Value",
		"fechaNacimiento": "#Control:fechaNacimiento/#Value",
		"haDonado": "#Control:haDonado/#Value",
		"generico1": "#Control:generico1/#Value",
		"generico2": "#Control:generico2/#Value",
		"generico3": "#Control:generico3/#Value"
	}
}