{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "create"
	},
	"OnFailure": "/DreamsBank/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"Service": "/DreamsBank/Services/dreamsbankmov.service",
		"EntitySet": "Asignacion"
	},
	"Properties": {
		"aspirante_identificacion": "#Page:AsignarXDonante_Resumen/#Control:idAspirante_Asignar/#Value",
		"donante_identificacion": "#Page:AsignarXDonante_Resumen/#Control:idDonante_Asignar/#Value"
	}
}