{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavTo_Asignar_SeleccionDonante"
	},
	"PageToOpen": "/DreamsBank/Pages/KnowledgePeople/Nuevo Proceso/Asignar_SeleccionDonante.page"
}