{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "AsignarXEmpresa_seleccionempresa"
	},
	"PageToOpen": "/DreamsBank/Pages/KnowledgeRun/Nuevo Proceso/AsignarxEmpresa_Seleccionempresa.page"
}