{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/DreamsBank/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/DreamsBank/Actions/UpdateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "Producto",
		"Service": "/DreamsBank/Services/dreamsbankmov.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"id": "#Control:id/#Value",
		"nombre_producto": "#Control:nombre_producto/#Value",
		"descripcion": "#Control:descripcion/#Value",
		"valor": "#Control:valor/#Value",
		"tipo": "#Control:tipo/#Value",
		"modalidad": "#Control:modalidad/#Value",
		"ciudad": "#Control:ciudad/#Value",
		"universidad": "#Control:universidad/#Value",
		"fabricante": "#Control:fabricante/#Value"
	}
}