{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "OnWillUpdate"
	},
	"Message": "Una nueva version de la aplicación está disponible, desea actualizar?",
	"Title": "Nueva version disponible",
	"OKCaption": "Actualizar",
	"CancelCaption": "Después"
}